# Generated by Django 4.0.5 on 2022-06-02 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Arcticle',
            new_name='Article',
        ),
    ]
