# Generated by Django 4.0.5 on 2022-06-02 15:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_arcticle_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='last_edit_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 2, 15, 29, 55, 539883, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
